#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="${ALI_WORKSPACE_DIR:-$(cd "$SCRIPT_DIR/.." && pwd)}"
cd "$REPO_DIR"

if ! git rev-parse --show-toplevel >/dev/null 2>&1; then
  echo "Not a git repository: $REPO_DIR" >&2
  exit 1
fi

MODE="${1:-status}"
RAW_NODE_NAME="${ALI_NODE_NAME:-$(hostname -s)}"
NODE_NAME="$(printf '%s' "$RAW_NODE_NAME" | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9_-' '-')"
TIMESTAMP="$(date '+%Y-%m-%d %H:%M:%S %Z')"
WIP_BRANCH="wip/$NODE_NAME"
WIP_DIR="$REPO_DIR/ali/WIP/$NODE_NAME"
WIP_STATUS_FILE="$WIP_DIR/STATUS.md"
DEFAULT_BRANCH_RAW="$(git symbolic-ref refs/remotes/origin/HEAD --short 2>/dev/null || true)"
DEFAULT_BRANCH="${DEFAULT_BRANCH_RAW#origin/}"
DEFAULT_BRANCH="${DEFAULT_BRANCH:-main}"
CURRENT_BRANCH="$(git symbolic-ref --quiet --short HEAD 2>/dev/null || git rev-parse --short HEAD)"

is_dirty() {
  ! git diff --quiet --ignore-submodules -- || \
  ! git diff --cached --quiet --ignore-submodules -- || \
  [[ -n "$(git ls-files --others --exclude-standard)" ]]
}

print_branch_state() {
  local branch="$1"
  local upstream
  upstream="$(git rev-parse --abbrev-ref "${branch}@{upstream}" 2>/dev/null || true)"
  if [[ -z "$upstream" ]]; then
    printf 'branch=%s upstream=none ahead=0 behind=0\n' "$branch"
    return
  fi

  local counts ahead behind
  read -r behind ahead <<< "$(git rev-list --left-right --count "${upstream}...${branch}")"
  printf 'branch=%s upstream=%s ahead=%s behind=%s\n' "$branch" "$upstream" "$ahead" "$behind"
}

sync_current_branch_if_safe() {
  local upstream ahead behind
  upstream="$(git rev-parse --abbrev-ref "${CURRENT_BRANCH}@{upstream}" 2>/dev/null || true)"
  if [[ -z "$upstream" ]]; then
    echo "No upstream set for $CURRENT_BRANCH; skipped pull/push."
    return
  fi

  read -r behind ahead <<< "$(git rev-list --left-right --count "${upstream}...${CURRENT_BRANCH}")"

  if (( behind > 0 && ahead == 0 )); then
    echo "Fast-forwarding $CURRENT_BRANCH from $upstream"
    git pull --ff-only
  elif (( behind > 0 && ahead > 0 )); then
    echo "Branch $CURRENT_BRANCH diverged from $upstream; skipped auto-pull/push."
    return
  fi

  read -r behind ahead <<< "$(git rev-list --left-right --count "${upstream}...${CURRENT_BRANCH}")"

  if (( ahead > 0 && behind == 0 )); then
    echo "Pushing $CURRENT_BRANCH to $upstream"
    git push
  else
    echo "Branch $CURRENT_BRANCH already synchronized with $upstream"
  fi
}

clear_merged_wip_branch() {
  git fetch --all --prune >/dev/null 2>&1 || true
  if git show-ref --verify --quiet "refs/remotes/origin/$WIP_BRANCH" && \
     git show-ref --verify --quiet "refs/remotes/origin/$DEFAULT_BRANCH" && \
     git merge-base --is-ancestor "origin/$WIP_BRANCH" "origin/$DEFAULT_BRANCH"; then
    echo "Removing merged remote branch origin/$WIP_BRANCH"
    git push origin --delete "$WIP_BRANCH" >/dev/null 2>&1 || true
    git branch -D "$WIP_BRANCH" >/dev/null 2>&1 || true
  fi
}

write_wip_status() {
  mkdir -p "$WIP_DIR"
  local changed_files status_output diffstat
  changed_files="$(git status --short)"
  diffstat="$(git diff --stat HEAD -- . || true)"
  cat > "$WIP_STATUS_FILE" <<EOF
# WIP status for $NODE_NAME

- Updated: $TIMESTAMP
- Node: $NODE_NAME
- Source branch: $CURRENT_BRANCH
- Default branch: $DEFAULT_BRANCH
- HEAD: $(git rev-parse --short HEAD)

## Working tree summary

\`\`\`
$changed_files
\`\`\`

## Diffstat vs HEAD

\`\`\`
$diffstat
\`\`\`

## Notes

- This file is auto-generated by \`ali/session-sync.sh end\` when the tree is dirty.
- The actual checkpoint lives on branch \`$WIP_BRANCH\`.
- Promote completed work back to \`$DEFAULT_BRANCH\` with an intentional commit or PR.
EOF
}

show_wip_state() {
  echo
  echo "WIP branches on origin:"
  git for-each-ref refs/remotes/origin/wip --format='  %(refname:short) | %(committerdate:iso8601) | %(subject)' || true
  echo
  if git show-ref --verify --quiet "refs/remotes/origin/$WIP_BRANCH"; then
    echo "Current node WIP branch exists: origin/$WIP_BRANCH"
    git log --oneline -n 3 "origin/$WIP_BRANCH" | sed 's/^/  /'
  else
    echo "Current node WIP branch: none"
  fi
}

case "$MODE" in
  start)
    echo "== Ali session start sync =="
    git fetch --all --prune
    clear_merged_wip_branch
    if is_dirty; then
      echo "Working tree is dirty; skipped auto-pull on $CURRENT_BRANCH"
    else
      sync_current_branch_if_safe
    fi
    echo
    git status --short --branch
    show_wip_state
    ;;

  end)
    echo "== Ali session end sync =="
    git fetch --all --prune
    clear_merged_wip_branch
    if is_dirty; then
      echo "Dirty tree detected; checkpointing to $WIP_BRANCH"
      write_wip_status
      if [[ "$CURRENT_BRANCH" != "$WIP_BRANCH" ]]; then
        git checkout -B "$WIP_BRANCH"
      fi
      git add -A
      if git diff --cached --quiet --ignore-submodules --; then
        echo "No staged delta after WIP preparation; nothing to commit."
      else
        git commit -m "wip($NODE_NAME): checkpoint $TIMESTAMP from $CURRENT_BRANCH"
        git push -u origin "$WIP_BRANCH"
      fi
      if [[ "$CURRENT_BRANCH" != "$WIP_BRANCH" ]]; then
        git checkout "$CURRENT_BRANCH"
      fi
      echo "Checkpoint available on origin/$WIP_BRANCH"
    else
      sync_current_branch_if_safe
      echo "Clean tree; no WIP checkpoint needed."
    fi
    ;;

  clear)
    echo "== Ali WIP clear =="
    clear_merged_wip_branch
    if git show-ref --verify --quiet "refs/remotes/origin/$WIP_BRANCH"; then
      echo "WIP branch still exists and is not merged into origin/$DEFAULT_BRANCH: origin/$WIP_BRANCH"
      exit 2
    fi
    echo "No outstanding merged WIP branch for $NODE_NAME"
    ;;

  status)
    echo "== Ali session sync status =="
    git fetch --all --prune
    clear_merged_wip_branch
    git status --short --branch
    echo
    print_branch_state "$CURRENT_BRANCH"
    show_wip_state
    ;;

  *)
    echo "Usage: $0 [start|end|status|clear]" >&2
    exit 1
    ;;
esac
